# Auto-gerado: mapa de substituição (origem -> alvo)
mapping = {
    'T': 'A',
    'W': 'O',
    'G': 'F',
    'V': 'T',
    'C': 'H',
    'O': 'E',
    'J': 'P',
    'I': 'R',
    'L': 'J',
    'U': 'U',
    'A': 'D',
    'N': 'I',
    'S': 'C',
    'M': 'S',
    'D': 'Y',
    'H': 'W',
    'K': 'L',
    'P': 'X',
    'Z': 'N',
    'B': 'V',
    'X': 'B',
    'Q': 'M',
    'R': 'G',
    'Y': 'K',
}
